/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techie;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author abdul
 */
public class levels extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public levels() {
        initComponents();

        ImageIcon backgroundIcon = new ImageIcon("levelsBackGround.png");
        Image backGroundimg = backgroundIcon.getImage().getScaledInstance(backGroundLabel1.getWidth(), backGroundLabel1.getHeight(), Image.SCALE_SMOOTH);
        backgroundIcon = new ImageIcon(backGroundimg);
        backGroundLabel1.setIcon(backgroundIcon);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Level1Button = new javax.swing.JButton();
        Level2Button = new javax.swing.JButton();
        Level3Button = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        ranking = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backGroundLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        Level1Button.setBackground(new java.awt.Color(39, 43, 58));
        Level1Button.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Level1Button.setForeground(new java.awt.Color(255, 255, 255));
        Level1Button.setText("Level 1");
        Level1Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        Level1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level1Button);
        Level1Button.setBounds(80, 350, 180, 30);

        Level2Button.setBackground(new java.awt.Color(39, 43, 59));
        Level2Button.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Level2Button.setForeground(new java.awt.Color(255, 255, 255));
        Level2Button.setText("Level 2");
        Level2Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        Level2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level2ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level2Button);
        Level2Button.setBounds(80, 400, 180, 30);

        Level3Button.setBackground(new java.awt.Color(39, 43, 59));
        Level3Button.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Level3Button.setForeground(new java.awt.Color(255, 255, 255));
        Level3Button.setText("Level 3");
        Level3Button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        Level3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level3ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Level3Button);
        Level3Button.setBounds(80, 450, 180, 30);

        welcomeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome Mona");
        getContentPane().add(welcomeLabel);
        welcomeLabel.setBounds(10, 30, 110, 30);

        ranking.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ranking.setText("Ranking");
        ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingMouseClicked(evt);
            }
        });
        getContentPane().add(ranking);
        ranking.setBounds(250, 36, 50, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("<html> Level up!<br> Conquer the first level and unlock the next.<br>  Are you ready for the challenge?  </html?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 190, 310, 110);
        getContentPane().add(backGroundLabel1);
        backGroundLabel1.setBounds(0, 0, 330, 600);

        setSize(new java.awt.Dimension(346, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Level3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level3ButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Level3ButtonActionPerformed

    private void Level2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Level2ButtonActionPerformed

    private void Level1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Level1ButtonActionPerformed

    private void rankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_rankingMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new levels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Level1Button;
    private javax.swing.JButton Level2Button;
    private javax.swing.JButton Level3Button;
    private javax.swing.JLabel backGroundLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ranking;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
